import { GoogleGenerativeAI, SchemaType } from '@google/generative-ai';

/**
 * AI Content Generation Service
 *
 * Handles AI-powered product content generation using Google Generative AI
 */

/**
 * Product content generation request
 */
export interface ProductContentRequest {
  productName: string;
  category?: string;
}

/**
 * Predicted product attributes from AI
 */
export interface PredictedAttributes {
  brand?: string;
  weight_volume?: string;
  flavor_type?: string;
  origin?: string;
  main_ingredients?: string;
}

/**
 * Marketing content generated by AI
 */
export interface MarketingContent {
  short_description: string;
  detailed_description: string;
}

/**
 * Complete AI response for product content
 */
export interface ProductContentResponse {
  predicted_attributes: PredictedAttributes;
  marketing_content: MarketingContent;
}

/**
 * Get Google Generative AI API key from environment
 */
function getApiKey(): string {
  const apiKey = process.env.NEXT_PUBLIC_GOOGLE_GENAI_API_KEY;

  if (!apiKey) {
    throw new Error(
      'Google GenAI API key not configured. Please add NEXT_PUBLIC_GOOGLE_GENAI_API_KEY to .env.local'
    );
  }

  return apiKey;
}

/**
 * Generate product content using AI
 *
 * @param request - Product content generation request
 * @returns Promise resolving to generated content
 * @throws Error on failure
 */
export async function generateProductContent(
  request: ProductContentRequest
): Promise<ProductContentResponse> {
  const { productName, category = '' } = request;

  if (!productName || productName.trim() === '') {
    throw new Error('Product name is required');
  }

  const apiKey = getApiKey();
  const genAI = new GoogleGenerativeAI(apiKey);

  const model = genAI.getGenerativeModel({
    model: 'gemini-2.0-flash',
    generationConfig: {
      responseMimeType: 'application/json',
      responseSchema: {
        type: SchemaType.OBJECT,
        required: ["predicted_attributes", "marketing_content"],
        properties: {
          // AI predicts technical attributes
          predicted_attributes: {
            type: SchemaType.OBJECT,
            required: ['brand', 'weight_volume', 'flavor_type', 'origin', 'main_ingredients'],
            properties: {
              brand: {
                type: SchemaType.STRING,
                description: 'Thương hiệu dự đoán'
              },
              weight_volume: {
                type: SchemaType.STRING,
                description: 'Trọng lượng/Thể tích (ví dụ: 75g, 1L). Nếu không rõ hãy ước lượng chuẩn chung.'
              },
              flavor_type: {
                type: SchemaType.STRING,
                description: 'Hương vị hoặc loại (ví dụ: Tôm chua cay, Bò hầm)'
              },
              origin: {
                type: SchemaType.STRING,
                description: 'Xuất xứ (Việt Nam/Thái Lan...)'
              },
              main_ingredients: {
                type: SchemaType.STRING,
                description: 'Thành phần chính ước đoán'
              },
            },
          },
          // Marketing content based on above info
          marketing_content: {
            type: SchemaType.OBJECT,
            required: ["short_description", "detailed_description"],
            properties: {
              short_description: {
                type: SchemaType.STRING,
                description: 'Mô tả ngắn gọn, súc tích (1-2 câu), dùng cho meta description SEO'
              },
              detailed_description: {
                type: SchemaType.STRING,
                description: 'Mô tả chi tiết, hấp dẫn, khoảng 3-5 đoạn văn, sử dụng HTML tags như <p>, <ul>, <li>, <strong>'
              },
            },
          },
        },
      },
    },
  });

  const prompt = `
Bạn là chuyên gia dữ liệu sản phẩm FMCG (Hàng tiêu dùng nhanh).
Nhiệm vụ: Từ Tên sản phẩm và Danh mục, hãy SUY LUẬN ra các thông số kỹ thuật và viết mô tả.

Input:
- Tên: "${productName}"
- Danh mục: "${category || 'Không xác định'}"

Yêu cầu quan trọng:
0. Định dạng trả về: JSON (BẮT BUỘC).
1. Nếu sản phẩm nổi tiếng (ví dụ: "Hảo Hảo"), hãy điền thông tin chính xác từ kiến thức của bạn.
2. Nếu sản phẩm chung chung (ví dụ: "Cá viên"), hãy điền thông số phổ biến nhất trên thị trường (ví dụ: 500g).
3. Mục 'brand': Nếu không xác định được, để là "Generic" hoặc "OEM".
4. Viết mô tả hấp dẫn dựa trên các thông số đã suy luận.
5. short_description: Ngắn gọn, súc tích (1-2 câu), dùng cho meta description SEO.
6. detailed_description: Chi tiết, hấp dẫn, khoảng 3-5 đoạn văn, sử dụng HTML tags như <p>, <ul>, <li>, <strong> để format.

  `.trim();
  try {
    const result = await model.generateContent(prompt);
    const responseText = result.response.text();
    const data = JSON.parse(responseText) as ProductContentResponse;

    return data;
  } catch (error) {
    console.error('Failed to generate product content:', error);

    if (error instanceof Error) {
      throw new Error(`Content generation failed: ${error.message}`);
    }

    throw new Error('Content generation failed: Unknown error');
  }
}

/**
 * Validate product content request
 */
export function validateContentRequest(
  request: ProductContentRequest
): { valid: boolean; error?: string } {
  if (!request.productName || request.productName.trim() === '') {
    return {
      valid: false,
      error: 'Product name is required',
    };
  }

  if (request.productName.length > 200) {
    return {
      valid: false,
      error: 'Product name is too long (max 200 characters)',
    };
  }

  return { valid: true };
}
